### ISSUE TITLE
Build fails with `Recursion stack not enough.`

### ISSUE THREAD

**Issue by jketema** [Nelson-numerical-software/nelson#731]
For some experiments I'm trying to set up a CodeQL job identical to yours, except that I'm using a somewhat differently configured Ubuntu 22.04 runner. Unfortunately on that particular runner I see the build failing with the error below. Could you offer some guidance how to solve this or work around this? We did play around a bit with `ulimit`, but that seemed to have little effect. Thanks.

```
FAILED: modules/main/CMakeFiles/Name /home/runner/work/codeql-dca-worker/codeql-dca-worker/modules/main/CMakeFiles/Name 
cd /home/runner/work/codeql-dca-worker/codeql-dca-worker/modules/main && /home/runner/work/codeql-dca-worker/codeql-dca-worker/bin/linux/nelson-cli --nousermodules --noipc --quiet --file /home/runner/work/codeql-dca-worker/codeql-dca-worker/bin/linux/../../tools/gettext/generatemo.m
Recursion stack not enough.
Please set C recursion stack to 62914560
Current C stack is: 16777216
```

### Your Environment

- OS: Ubuntu 22.04 
- Nelson version: 3479d3b1b3a8a7fa5e4dc246546b967bdbc8631a (this is completely arbitrarily chosen)

**Comment by Nelson-numerical-software** [comment]
Thanks to use Nelson as experiment for some CodeQL tests :)

This message is due to that it is not possible by Nelson to extend RLIMIT_STACK to size 60* 1024 * 1024 used by Nelson.
It is the first time that I have this trouble. Even on small pc (raspberry or sbc) It was until now ok to set this size.
Could I have more information on your "dev" environment ? ubuntu 22.04 with low ram, 1Go ?

What is the result of `ulimit -a` ? 
can you set `ulimit -s 62914560` ?

**Comment by Nelson-numerical-software** [comment]
only for experiment,  I reduced default size 
https://github.com/Nelson-numerical-software/nelson/tree/rlimit_limited 
I would prefer to not change this default until more tests

**Comment by jketema** [comment]
Thanks. I'll try to dig up the needed information. From your answer I do get the feeling that the runner might be misconfigured, so I'll also investigate that.
