### ISSUE TITLE
Nelson vs Scilab

### ISSUE THREAD

**Issue by moueza** [Nelson-numerical-software/nelson#816]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nelson-numerical-software** [comment]
Nelson is NOT Scilab.

Nelson is a clean fresh development from zero for the code using modern librairies and modern development process and tools where others uses librairies of the previous century.

Syntax is very similar to GNU Octave or MATLAB® so that most programs are easily portable.
It is NOT compatible with Scilab (and it will be never).
